modLoader = "javafml"
loaderVersion = "[1,)"
issueTrackerURL = "https://github.com/Mystic-Creations/MysticLib/issues"
license = "All Rights Reserved"

[[mods]]
modId = "mysticlib"
version = "${mod_version}"
displayName = "MysticLib"
description = "Multi-tool library mod for mods by Mystic Creations Team"
authors = "Mystic Creations Team"
logoFile = "icon.png"

[[dependencies.mysticlib]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version_range},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mysticlib]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.mysticlib]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_api_version},)"
ordering = "AFTER"
side = "BOTH"
